apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-dev-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: local-dev-ui
  template:
    metadata:
      labels:
        app: local-dev-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-local-dev-demo:0.2
        name: local-dev-ui
        ports:
        - containerPort: 80
